### ISSUE TITLE
Class referenced in the layout file, `xyz.schwaab.avvylib.AvatarView`, was not found in the project or the libraries.

### ISSUE THREAD

**Issue by TrueKage** [vitorhugods/AvatarView#14] opened 2020-12-02 05:29 UTC
Cannot resolve class xyz.schwaab.avvylib.AvatarView

--In my new project I'm not able to resolve the avatar view while using gradle dependency.

**Comment by vitorhugods** [comment] 2020-12-03 19:24
Is this the build output or just the IDE's inspection?

There's no obvious reason for the class not to be found when declaring the dependency correctly.

How is your configuration? Can you share logs/stacktrace?

**Comment by TrueKage** [comment] 2020-12-04 10:07
This is build output.
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
classpath "com.android.tools.build:gradle:4.1.1"

**Comment by vitorhugods** [comment] 2020-12-07 11:55
By build output, is this the `gradlew build` task you're running?
What are the steps you're doing to trigger this error?
Can you post a sample project reproducing this issue?

I fail to see how this is reproducible. Some clarification is needed.

**Comment by vitorhugods** [comment] 2020-12-22 23:41
@TrueKage I figured this out!

The problem is that I fucked up before.
The version `1.1.0` available in JCenter is broken, and the AvatarView class is missing.

I wasn't able to reproduce this, because I didn't have jCenter included in my repositories.

I released a new version called `1.1.1`, can you try with this one?

**Comment by vitorhugods** [comment] 2020-12-24 17:26
I'll close this for now, as I managed to test the `1.1.1` version in multiple projects, in different CI/CD tools and the dependency was downloaded successfuly, even without needing to declare the bintray repository. JCenter is enough now.

If you face this issue again, please come here and I'll re-open the issue.

**Closed by vitorhugods** 2020-12-24 17:26 UTC
Labels: implementation help, needs info

**Comment by TrueKage** [comment] 2020-12-25 08:56
It's Working. Thanks
